version: '3.7'
services:
  storage:
    image: pubsub/storage
    env_file:
      - ./config.env
    networks:
      - minimesh
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "8088:8088"

networks:
  minimesh:
    external: true
